apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: tcp-activation
      port: 3306
      targetPort: 3306
      nodePort: 31306
      protocol: TCP