apiVersion: v1
kind: Service
metadata:
  name: kms
spec:
  type: NodePort
  selector:
    app: kms
  ports:
    - name: tcp-activation
      port: 1688
      targetPort: 1688
      nodePort: 31688
      protocol: TCP