apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
