apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
