apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-autodiscover
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/pkoperwas/argocd-rke2-gitops-manifests.git'
        revision: HEAD
        directories:
          - path: 'apps/*'
        requeueAfterSeconds: 30  
    - git:
        repoURL: 'https://github.com/pkoperwas/argocd-rke2-gitops-manifests.git'
        revision: HEAD
        directories:
          - path: 'cluster-config/*'
        requeueAfterSeconds: 30  
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/pkoperwas/argocd-rke2-gitops-manifests.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true